spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: false
    generate-ddl: true

  kafka:
    bootstrap-servers: 34.64.55.76:9092,34.64.55.76:9093,34.64.55.76:9094

    producer:
      properties:
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "*"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

    consumer:
      group-id: point-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

cloud:
  aws:
    s3:
      bucket: barrier-free-friends
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${SECRET_ACCESS_KEY}