spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/v1/user/**
          filters:
            - 'RewritePath=/v1/user/(?<path>.*), /\${path}'

        - id: point-service
          uri: lb://point-service
          predicates:
            - Path=/v1/point/**
          filters:
            - 'RewritePath=/v1/point/(?<path>.*), /\${path}'

        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/v1/report/**
          filters:
            - 'RewritePath=/v1/report/(?<path>.*), /\${path}'

        - id: spot-service
          uri: lb://spot-service
          predicates:
            - Path=/v1/spot/**
          filters:
            - 'RewritePath=/v1/spot/(?<path>.*), /\${path}'